// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOZTTef2jJ1rUFHDhL6oajiVa60q5piQ',
    appId: '1:229699066727:web:55a3c8f02bcfedbc92edc2',
    messagingSenderId: '229699066727',
    projectId: 'umos-2024',
    authDomain: 'umos-2024.firebaseapp.com',
    storageBucket: 'umos-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRODD1oaHP8jLsd5sNK3smMWemSZXHG7Q',
    appId: '1:229699066727:android:d6d2f0ffe62f818792edc2',
    messagingSenderId: '229699066727',
    projectId: 'umos-2024',
    storageBucket: 'umos-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB22bsrE7_ehzFCXLBkKIgNyC7eLDQBFpg',
    appId: '1:229699066727:ios:f907ebcd1bc1abab92edc2',
    messagingSenderId: '229699066727',
    projectId: 'umos-2024',
    storageBucket: 'umos-2024.appspot.com',
    iosBundleId: 'com.example.umos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB22bsrE7_ehzFCXLBkKIgNyC7eLDQBFpg',
    appId: '1:229699066727:ios:9972a8eec248cc2192edc2',
    messagingSenderId: '229699066727',
    projectId: 'umos-2024',
    storageBucket: 'umos-2024.appspot.com',
    iosBundleId: 'com.example.umos.RunnerTests',
  );
}
